/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

class HelloGradlePluginPlugin: Plugin<Settings> {
    override fun apply(target: Settings) {
        println("hello, world")
    }
}
